import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export async function generateCustomPDF(booking) {
  const doc = new jsPDF();

  // Header Travel Agent (dummy, bisa diganti logo/nama asli)
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text("TRAVEL AGENT TRAVELNESIA", 14, 15);
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text("Jl. Malang", 14, 20);
  doc.text("Telp: (021) 12345678 | Email: info@travelnesia.co.id", 14, 25);

  // Judul Invoice
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text("INVOICE PACKAGE", 105, 38, { align: "center" });
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(14, 42, 196, 42);

  // Info Invoice & Customer
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  const infoY = 48;
  doc.text(`No. Invoice: ${getPatentCode(booking.payment)}`, 14, infoY);


  // Info Paket & Kendaraan (kanan)
  let rightY = infoY;
  doc.text(`Paket: ${booking.package?.name ?? "-"}`, 120, rightY);
  doc.text(`Kendaraan: ${booking.vehicle?.name ?? "-"}`, 120, rightY + 7);
  doc.text(`Jumlah Penumpang: ${booking.jumlah_penumpang ?? '-'}`, 120, rightY + 14);
    doc.text(`Tanggal: ${
    booking.payment?.payment_date
      ? new Date(booking.payment.payment_date).toLocaleString("id-ID")
      : "-"
  }`, 14, infoY + 7);
  doc.text(`Customer: ${booking.user?.name ?? "-"}`, 14, infoY + 14);
  doc.text(`Status: ${booking.status ?? "-"}`, 14, infoY + 21);
  doc.text(`Tanggal Booking: ${booking.booking_date
    ? new Date(booking.booking_date).toLocaleString("id-ID")
    : booking.createdAt
    ? new Date(booking.createdAt).toLocaleString("id-ID")
    : "-"}`, 120, rightY + 21);

  // Tabel Invoice (Deskripsi, Qty, Harga, Subtotal)
  autoTable(doc, {
    startY: infoY + 30,
    head: [["Paket", "Jumlah Penumpang", "Harga Paket", "Subtotal"]],
    body: [
      [
        booking.package?.name ?? "-",
        booking.jumlah_penumpang ?? '-',
        booking.payment?.amount
          ? new Intl.NumberFormat("id-ID", {
              style: "currency",
              currency: "IDR",
              minimumFractionDigits: 0,
            }).format(Math.round((booking.payment.amount || 0) / (booking.jumlah_penumpang || 1)))
          : "-",
        booking.payment?.amount
          ? new Intl.NumberFormat("id-ID", {
              style: "currency",
              currency: "IDR",
              minimumFractionDigits: 0,
            }).format(booking.payment.amount)
          : "-",
      ],
    ],
    styles: {
      fontSize: 11,
      cellPadding: 3,
      textColor: [0, 0, 0],
      lineColor: [0, 0, 0],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: [0, 0, 0],
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center',
    },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    rowStyles: { fillColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
    tableLineColor: [0, 0, 0],
    tableLineWidth: 0.2,
    columnStyles: {
      1: { halign: 'center', cellWidth: 25 },
      2: { halign: 'right', cellWidth: 40 },
      3: { halign: 'right', cellWidth: 40 },
    },
  });

  // Ringkasan Total & Info Pembayaran
  const afterTableY = doc.lastAutoTable.finalY + 8;
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text("Total", 120, afterTableY);
  doc.text(
    booking.payment?.amount
      ? new Intl.NumberFormat("id-ID", {
          style: "currency",
          currency: "IDR",
          minimumFractionDigits: 0,
        }).format(booking.payment.amount)
      : "-",
    180,
    afterTableY,
    { align: "right" }
  );
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text(`Metode Pembayaran: ${booking.payment?.payment_method ?? '-'}`, 120, afterTableY + 7);
  doc.text(`Status Transaksi: ${booking.payment?.transaction?.status ?? '-'}`, 120, afterTableY + 14);

  // Catatan/Thank you note
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(
    "Terima kasih telah menggunakan layanan Travelnesia.",
    14,
    afterTableY + 28
  );
  doc.setTextColor(120);
  doc.text(
    "Struk ini sah tanpa tanda tangan.",
    14,
    afterTableY + 34
  );

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(180);
  doc.text(
    "Generated by Travelnesia System",
    105,
    doc.internal.pageSize.getHeight() - 8,
    { align: "center" }
  );

  // Return DataURL for preview/download
  const pdfBlob = doc.output("blob");
  return URL.createObjectURL(pdfBlob);
}

// Helper untuk kode booking
function getPatentCode(payment) {
  if (!payment) return "-";
  const id = payment.id || "-";
  const date = payment.payment_date || payment.createdAt;
  if (!date || !id) return "-";
  const d = new Date(date);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  return `${year}${month}/${id}`;
}
